pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pipe: atlassian/ssh-run:0.2.4
            variables:
              SSH_USER: 'molvest'
              SERVER: 'i-sd.ru'
              COMMAND: 'sh deploy.smart.sh'