<?php

return [
  '57' => [
    'page_id' => 57,
    'company_id' => 1809,
    'usergroup_id' => [544],
    'fields_map' => [
       'firstname' => '57',
       'password' => '58',
       'phone' => '59',
       's_phone' => '59',
       'email' => '60',
       'user_login' => '60',
       'address' => '61',
       'b_address' => '61',
       's_address' => '61',
       'b_firstname' => '57',
    ],
  ],
  '56' => [
    'page_id' => 56,
    'company_id' => 16,
    'usergroup_id' => [9],
    'fields_map' => [
       'firstname' => '56',
       'password' => '94',
       'email' => '49',
       'user_login' => '49',
       'b_firstname' => '44',
       'b_address' => '45',
       's_address' => '46',
       'fax' => '47',
       'b_firstname' => '56',
    ],
    'render_document' => 60,
    'document_map' => [
      '56' => 'director',
      '55' => 'k_ch',
      '54' => 'bik',
      '53' => 'bank',
      '52' => 'r_ch',
      '51' => 'ogrn',
      '50' => 'kpp',
      '44' => 'company',
      '45' => 'ur_address',
      '46' => 'mail_address',
      '47' => 'inn'
    ],
  ],
  '59' => [
    'page_id' => 59,
    'company_id' => 16,
    'usergroup_id' => [542],
    'fields_map' => [
       'firstname' => '93',
       'password' => '95',
       'email' => '86',
       'user_login' => '86',
       'b_firstname' => '82',
       'b_address' => '83',
       's_address' => '84',
       'fax' => '85',
       'b_firstname' => '93',
    ],
    'render_document' => 60,
    'document_map' => [
      '93' => 'director',
      '92' => 'k_ch',
      '91' => 'bik',
      '90' => 'bank',
      '89' => 'r_ch',
      '88' => 'ogrn',
      '87' => 'kpp',
      '82' => 'company',
      '83' => 'ur_address',
      '84' => 'mail_address',
      '85' => 'inn'
    ]
  ],
  '61' => [
    'page_id' => 61,
    'company_id' => 1797,
    'usergroup_id' => [549],
    'fields_map' => [
      'firstname' =>'96',
      'password' =>'97',
      'email' =>'99',
      'user_login' =>'99',
      'phone' =>'98',
      's_phone' => '98',
      's_address' => ['100', '126', '127', '128'],
      's_address2' => ['100', '126', '127', '128'],
      'b_firstname' => '96',
    ],
  ],
  '62' => [
    'page_id' => 62,
    'company_id' => 1805,
    'usergroup_id' => [550],
    'fields_map' => [
       'firstname' => '106',
       'password' => '107',
       'email' => '109',
       'user_login' => '109',
       'phone' => '108',
       's_phone' => '108',
       's_address' => '110',
       's_address2' => '110',
       'b_firstname' => '106',
    ],
  ],
  '64' => [
    'page_id' => 64,
    'company_id' => 1807,
    'usergroup_id' => [554],
    'fields_map' => [
       'firstname' => '129',
       'password' => '130',
       'email' => '132',
       'user_login' => '132',
       'phone' => '131',
       's_phone' => '131',
       's_address' => '133',
       's_address2' => '133',
       's_client_code' => '9999',
       'b_client_code' => '9999',
       'b_firstname' => '129',
    ],
  ],
  '63' => [
    'page_id' => 63,
    'company_id' => 46,
    'usergroup_id' => [564],
    'fields_map' => [
       'firstname' => '116',
       'phone' => '119',
       'email' => '119',
       'user_login' => '119',
       'password' => '117',
       's_phone' => '119',
       // 's_address' => '120',
       // 's_address2' => '120',
       // 's_client_code' => '9999',
       // 'b_client_code' => '9999',
       'b_firstname' => '116',
    ],
  ],
];
